### ISSUE TITLE
Crashing when updating list of addins

### ISSUE THREAD

**Issue by daattali** [daattali/addinslist#124]
Reported by @jeam-github in #123 

```
Looks like I have a similar problem. I've installed and am trying to use the addinslist addin within RStudio but encounter an error on selecting addinslist from the Addins menu in RStudio:
Loading required package: shiny

Listening on http://127.0.0.1:6507
pandoc: ~/Library/Application Support/addinsrepo/addins.md: openBinaryFile: does not exist (No such file or directory)
Warning: Error in : pandoc document conversion failed with error 1
  57: stop
  56: rmarkdown::pandoc_convert
  55: update_addins_file
  54: update_addins_list
  53: update_addins_list_values
  52: refresh_list
  51:
  49: server
Error : pandoc document conversion failed with error 1

This suggests to me that the markup file being produced cannot be found by pandoc. I can see what I think is the generated markup file in question at:
/Users/jim/Library/Application Support/addinsrepo/addins.md  

If my assumption above is correct, how do I go about fixing this so that pandoc finds the file to display?
```

**Comment by daattali** [comment]
@jeam-github the file path is created by the {rappdirs} package directly as you can see [here](https://github.com/daattali/addinslist/blob/19a98ccd7adf6a2bb7dc591ccdea4db92a2423ea/R/utils.R#L117-L119).

Can you try running `rappdirs::user_data_dir("addinsrepo", "daattali")` on your machine and see what it returns, if it's "~" or "/Users/jim"? Similarly, try just running `rappdirs::user_data_dir("test")`. It'll be very strange if for most people on Mac it returns the expanded version but for you it's not.

**Comment by jeam-github** [comment]
> rappdirs::user_data_dir("addinsrepo", "daattali")
[1] "~/Library/Application Support/addinsrepo"

> rappdirs::user_data_dir("test")
[1] "~/Library/Application Support/test"

It certainly returns "~"

**Comment by daattali** [comment]
What version of mac do you have? I'm surprised at this inconsistency, reported it to {rappdirs} https://github.com/r-lib/rappdirs/issues/37

Does it seem like pandoc is failing to read the file because of "~"? If you manually run `rmarkdown::pandoc_convert("/Users/jim/Library/Application Support/addinsrepo/addins.md", to = "html")` does that work? But running `rmarkdown::pandoc_convert("~/Library/Application Support/addinsrepo/addins.md", to = "html")` fails? Can you confirm the output of `path.expand("~")`?

**Comment by jeam-github** [comment]
Version of Mac:
Hardware Overview:

  Model Name:	iMac
  Model Identifier:	iMac15,1
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	3.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	235.0.0.0.0
  SMC Version (system):	2.22f16
  Serial Number (system):	C02NP3CDFY14
  Hardware UUID:	AFEAE160-1045-5C0B-8A83-96B6836553FE

System Software Overview:

  System Version:	macOS 10.15.7 (19H15)
  Kernel Version:	Darwin 19.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	Jim’s iMac
  Username:	Jim McIntosh (jim)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	8 days 22:08




> On 1/04/2021, at 4:45 AM, Dean Attali ***@***.***> wrote:
> 
> Does it seem like pandoc is failing to read the file because of "~"? If you manually run rmarkdown::pandoc_convert("/Users/jim/Library/Application Support/addinsrepo/addins.md", to = "html") does that work?

Yes, it produces HTML code that saved as file code.html displays perfectly in Safari.

> But running rmarkdown::pandoc_convert("~/Library/Application Support/addinsrepo/addins.md", to = "html") fails?


Yes, it fails:
> rmarkdown::pandoc_convert("~/Library/Application Support/addinsrepo/addins.md", to = "html")
pandoc: ~/Library/Application Support/addinsrepo/addins.md: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1

>  Can you confirm the output of path.expand("~")?

> path.expand("~")
[1] "/Users/jim"

**Comment by daattali** [comment]
Interesting. This seems like a bug in rmarkdown::pandoc_convert. Can you please help me with the following so that I can open an accurate bug report on {rmarkdown}:

- Confirm that `path.expand("~") == "/Users/jim"`
- Create a file at "~/test.md" that contains the text `# test`
- Confirm that `rmarkdown::pandoc_convert("/Users/jim/test.md", to = "html")` works
- Confirm that `rmarkdown::pandoc_convert("~/test.md", to = "html")` results in an error (please copy the error)

Thanks!

**Comment by jeam-github** [comment]
See below (apart from creation of the test file, all done in RStudio):

> On 1/04/2021, at 8:45 AM, Dean Attali ***@***.***> wrote:
> 
> 
> Interesting. This seems like a bug in rmarkdown::pandoc_convert. Can you please help me with the following so that I can open an accurate bug report on {rmarkdown}:
> 
> Confirm that path.expand("~") == "/Users/jim"
> path.expand("~")
[1] "/Users/jim"
> Create a file at "~/test.md" that contains the text # test
Created file:
/Users/jim/test.md
> Confirm that rmarkdown::pandoc_convert("/Users/jim/test.md", to = "html") works
> rmarkdown::pandoc_convert("/Users/jim/test.md", to = "html")
<h1 id="test">test</h1>
> Confirm that rmarkdown::pandoc_convert("~/test.md", to = "html") results in an error (please copy the error)
No error!!!

> rmarkdown::pandoc_convert("~/test.md", to = "html")
<h1 id="test">test</h1>

What is going on? What am I doing that is causing this problem?

**Comment by daattali** [comment]
Can you see whether the addins.md file that the original error complained about exists? If so, try runing the pandoc_convert function on that file, both using the expanded path and using the ~ path. This will help narrow down where the problem is.

**Comment by jeam-github** [comment]
See below:

> On 1/04/2021, at 10:09 AM, Dean Attali ***@***.***> wrote:
> 
> 
> Can you see whether the addins.md file that the original error complained about exists?
> 
I have just run it again, got the error, and yes, the addins.md file exists:
/Users/jim/Library/Application Support/addinsrepo/addins.md
> If so, try runing the pandoc_convert function on that file, both using the expanded path and using the ~ path. This will help narrow down where the problem is.
> 
>rmarkdown::pandoc_convert("/Users/jim/Library/Application Support/addinsrepo/addins.md", to = "html")
<h2 id="addinslist-table">
List of addins
</h2>
<p>If you made a useful RStudio addin, feel free to make a pull request <a href="https://github.com/daattali/addinslist#readme">on GitHub</a> to add it to the list.</p>
<table>
.
.
. etc

Which worked. Alternatively

>rmarkdown::pandoc_convert("~/Library/Application Support/addinsrepo/addins.md", to = "html")
pandoc: ~/Library/Application Support/addinsrepo/addins.md: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1

Which gave the error.

**Comment by daattali** [comment]
OK, I cannot reproduce this behaviour so you'll need to do some troubleshooting on your own and submit a bug report to {rmarkdown}.  

You've verified that (a) the file `/Users/jim/Library/Application Support/addinsrepo/addins.md` exists, (b) pandoc_convert on that file works, (c) pandoc_convert on the same file but with ~ doesn't work. That alone can be used to open an issue in their repo.

But it would be more useful if you can track it down some more. For example, we've already tried backtracking a few steps and we saw that the problem does not happen when you create a file at `/Users/jim/test.md`. So you should try creating another file `/Users/jim/Library/Application Support/addinsrepo/test.md` and see if that also fails with ~. If so, then try creating a file under `/Users/jim/Library/Application Support/test.md` and under `/Users/jim/Library/test.md` to see if one of those break. Maybe the issue is when there is tilde (~) expansion combined with a folder name that contains a space in it for example? It's very difficult for me to try to debug this without access to your machine but this is the sort of steps I would take. 

Please link to this issue in the rmarkdown issue you open so that we'll know when it's addressed!

**Comment by jeam-github** [comment]
It seems odd that the problem could be associated with the space in folder name  "Application Support" because this is an Apple folder name which everyone else, for which addinslist works fine, will have on their machines. However, I tried the following:

The following works OK with the test.md file in a folder with a space in the name and the full path:
> rmarkdown::pandoc_convert("/Users/jim/test folder/test.md", to = "html")
<h1 id="test">test</h1>

while this does not:
> rmarkdown::pandoc_convert("~/test folder/test.md", to = "html")
pandoc: ~/test folder/test.md: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1

However, following your suggestion with the space left out of the folder name, this does work
> rmarkdown::pandoc_convert("~/testfolder/test.md", to = "html")
<h1 id="test">test</h1>

I'm not sure what else to try - this seems to suggest it is the space in a folder name causing the problem, at least on my machine. But, as I said at the beginning, how can this be when everyone else running addinslist will also have a space in their "Application Support" folder name?

I'm not sure how to submit the evidence, and how much of it, as well as background info about addinslist, to {rmarkdown}?

**Comment by jeam-github** [comment]
And this also works, if I create a fake folder in Library folder and put the test file.md in that:
> rmarkdown::pandoc_convert("~/Library/ApplicationSupport/addinsrepo/test.md", to = "html")
<h1 id="test">test</h1>

whereas this, with the space, does not
> rmarkdown::pandoc_convert("~/Library/Application Support/addinsrepo/test.md", to = "html")
pandoc: ~/Library/Application Support/addinsrepo/test.md: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1

Pretty convincing...


________________________________________-


It seems odd that the problem could be associated with the space in folder name  "Application Support" because this is an Apple folder name which everyone else, for which addinslist works fine, will have on their machines. However, I tried the following:

The following works OK with the test.md file in a folder with a space in the name and the full path:
> rmarkdown::pandoc_convert("/Users/jim/test folder/test.md", to = "html")
<h1 id="test">test</h1>

while this does not:
> rmarkdown::pandoc_convert("~/test folder/test.md", to = "html")
pandoc: ~/test folder/test.md: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1

However, following your suggestion with the space left out of the folder name, this does work
> rmarkdown::pandoc_convert("~/testfolder/test.md", to = "html")
<h1 id="test">test</h1>

I'm not sure what else to try - this seems to suggest it is the space in a folder name causing the problem, at least on my machine. But, as I said at the beginning, how can this be when everyone else running addinslist will also have a space in their "Application Support" folder name?

I'm not sure how to submit the evidence, and how much of it, as well as background info about addinslist, to {rmarkdown}?

**Comment by daattali** [comment]
Reported to https://github.com/rstudio/rmarkdown/issues/2089

**Comment by daattali** [comment]
@jeam-github I applied a fix. Since I wasn't able to reproduce the issue, I cannot test if it works or not. Can you please re install this package from github (`remotes::install_github("daattali/addinslist")`) and verify that it works now

**Comment by jeam-github** [comment]
Yes, thanks, it works now. What was the problem?

**Comment by daattali** [comment]
The issue that we discovered, the one that I reported to rmarkdown.

**Comment by jeam-github** [comment]
OK, I see - thanks.

**Comment by sbalci** [comment]
Hi,

I am also experiencing same error on MacOS Catalina.

```r
> addinslist:::addinslistAddin()

Listening on http://127.0.0.1:5873
pandoc: ~/Library/Application Support/addinsrepo/addins.md: openBinaryFile: does not exist (No such file or directory)
Warning: Error in : pandoc document conversion failed with error 1
  57: stop
  56: rmarkdown::pandoc_convert
  55: update_addins_file
  54: update_addins_list
  53: update_addins_list_values
  52: refresh_list
  51: <Anonymous>
  49: server
Error : pandoc document conversion failed with error 1
```

**Comment by sbalci** [comment]
Hi, after restarting RStudio it worked. Thank you.

**Comment by bgwilli3** [comment]
Had the same issye as sbalc. Installing the lastest version of addinlist from github also worked. Thanks!!

**Comment by espinielli** [comment]
Same problem here using the version on CRAN.
After installing the latest version on github the problem disappears.

**Comment by daattali** [comment]
I'll update the package on CRAN today so that this fix will be around for everyone
