### ISSUE TITLE
Compare CRAN and GitHub versions

### ISSUE THREAD

**Issue by ottlngr** [daattali/addinslist#13]
This is a very very straightforward approach which parses the raw DESCRIPTION file on GitHub and the CRAN package website:

[https://gist.github.com/ottlngr/b83e9a8ae3631ceb9e941267574de9b2](https://gist.github.com/ottlngr/b83e9a8ae3631ceb9e941267574de9b2)

It's surprisingly fast (faster than some existing solutions).

**Comment by daattali** [comment]
:+1:  would you envision this happening to every package every time the list is fetched? I'm still a bit reluctant to add this because I don't see the package as being a "manager for installed packages", it's meant to just be a simple place to see the addins and install them if you want. I'm afraid of feature creeping... :p Although that's definitely a very subjective thing, there's a good chance other people agree with you

**Comment by ottlngr** [comment]
> would you envision this happening to every package every time the list is fetched?

I cannot think of another way yet, tbh.
I will try to get some kind of proof of concept working and leave this issue be for now.

**Comment by daattali** [comment]
I still can't think of any reasonable user interaction with the github/cran versions in a way that's simple and makes sense and is useful.  I think the current functionality (that doesn't show anything about the version) is good enoug, but I'm open to being convinced otherwise

**Comment by ottlngr** [comment]
You may just close this issue. 
I'll report back as soon as I've set up some kind of showcase.

**Comment by daattali** [comment]
Thanks, feel free to re-open in the future
