### ISSUE TITLE
Add the ability to search within the installer app

### ISSUE THREAD

**Issue by Stan125** [daattali/addinslist#14]
With a growing list of RStudio Add-Ins it will be important to search for a specific Add-In.

**Comment by daattali** [comment]
I purposely removed the "search" field to nake the UI simpler and less cluttered. I really really want to keep it as simple as possible, I don't want this to become some complex thing. For now there aren't enough addins to warrant a search (in my opinion?), if we do get a very long list where searching would be useful, we can add it in.

Also, I'm probably going to stop using DT and just use a regular HTML table because DT involves very complicated annoying code and has some bugs (that I reported to the DT repo last night) that will not happen with the much simpler approach of just using an HTML table

**Comment by daattali** [comment]
Search was added :)
