### ISSUE TITLE
This crashes RStudio on the Mac

### ISSUE THREAD

**Issue by cmbarton** [daattali/addinslist#74]
I've got RStudio Version 1.1.383 and R 3.4.1. All packages are up to dates. When I run addinslist, it crashes after opening a new window and attempting to update the list of addins.

**Comment by daattali** [comment]
Did this happen on with previous rstudio versions? Do you see an error in
the R console before crashing?

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by cmbarton** [comment]
Thanks for getting back to me Dean,

I seem to remember it happening in previous versions, but I can detail which ones. Sometimes it completely crashes RStudio. I just did it and it crashed a tiny bit more elegantly, allowing me to get a screenshot. It is probably not very informative. But I attach it anyway.

Michael

**Comment by daattali** [comment]
I don't see the screenshot attached.

Regardless, I believe anything that crashes rstudio should be reported to the rstudio team directly. Either using https://community.rstudio.com/ or on https://github.com/rstudio/rstudio

**Comment by cmbarton** [comment]
Here is the screenshot again.



I'm not optimistic about writing the rstudio team. They will say it is the package.

Michael

**Comment by daattali** [comment]
I think you need to upload the picture on github , it doesn't look like it gets attached through email.

The reason I say rstudio should be notified is because even if my package has terrible buggy code, it **should not crash rstudio**. If it crashes rstudio, that's a bug in the IDE and they should know

**Comment by cmbarton** [comment]
Here is the screenshot. I was replying through email because I was away from my computer. I'll contact the rstudio github too if I can. Thanks again for response.

<img width="2106" alt="addinlist_crash" src="https://user-images.githubusercontent.com/8967599/32127100-5157467a-bb29-11e7-9dd5-65d54897a270.png">

**Comment by genec1** [comment]
I have just installed `addinslist` and get an RStudio crash on Mac OS as well.

RStudio Version 1.2.5016
R Version "Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64"
Mac OS Version 10.15.1

**Comment by daattali** [comment]
Could you post at https://github.com/rstudio/rstudio/issues/1688 please?

**Comment by daattali** [comment]
Can anyone confirm if this is still happening?

**Comment by genec1** [comment]
I just tested on RStudio Version 1.4.904, MacOS 11.1, and it installed and ran successfully without crashing.

**Comment by cmbarton** [comment]
This seems to work fine for me now.

**Comment by daattali** [comment]
Great thanks!

**Comment by jeam-github** [comment]
I'm trying to use the addinslist addin within RStudio but encounter an error on selecting addinslist from the Addins menu in RStudio:
Loading required package: shiny

Listening on http://127.0.0.1:6507
pandoc: ~/Library/Application Support/addinsrepo/addins.md: openBinaryFile: does not exist (No such file or directory)
Warning: Error in : pandoc document conversion failed with error 1
  57: stop
  56: rmarkdown::pandoc_convert
  55: update_addins_file
  54: update_addins_list
  53: update_addins_list_values
  52: refresh_list
  51: <Anonymous>
  49: server
Error : pandoc document conversion failed with error 1

This suggests to me that the markup file being produced cannot be found by pandoc. I can see what I think is the generated markup file in question at:
/Users/jim/Library/Application Support/addinsrepo/addins.md  

If my assumption above is correct, how do I go about fixing this so that pandoc finds the file to display?
